### ISSUE TITLE
Moonset for previous day returned when moonset is after midnight local time.

### ISSUE THREAD

**Issue by w4jbm** [dminor/almanac#1]
I have been using the moonrise_moonset() function to build a table and comparing the results to other tables. I am doing this for a location in the Eastern timezone of the US which is currently in daylight savings time (a difference of -4 hours from UT) with a lat/lon of +33.6632, -85.1469. For the first four days of Oct, I get the following results:

1st, 17.618, 2.557
2nd, 18.711, 3.430
3rd, 19.697, 4.446
4th, 20.548, 5.5729

The moon set times for the 1st - 3rd are wrong. In trying to figure out what was going on I compared them to two different sources that show times of:

30th (of Sept), moon rise 12:30 pm, moon set 10:33 pm
1st, moon rise 1:39 pm, moon set 11:26 pm
2nd, moon rise 2:45 pm, (no moon set)
3rd,  moon set 12:27 am, moon rise 3:44 pm
4th, moon set 1:34 am, moon rise 4:34 pm

The moon set returned by the function seemed to be off by around an hour and I eventually found that it actually closely matches the moon set for the previous day. So for Oct 1st, the function returns moon rise at 13:37 and moon set at 22:33. The actual moon set should be 23:26. But if you look at the previous day (Sept 30th), the moon set for that day matches the erroneous returned value (with a time of 22:33).

This only seems to happen when the moon set time falls into the following day when using UT. (On the 1st, the moon set locally at 22:33 EDT which would have been 02:33 UT.

I don't see where the dt value that can be passed to the function has any impact on the values calculated.

**Comment by w4jbm** [comment]
I have worked around this by pulling today and tomorrows (adding 24 to the time) data in UT. I then change it to local time and can discard anything that goes negative for today and anything that is >24 for tomorrow. That logic will work for North America, but would fail for any place where UT is behind local time instead of ahead of it.

**Comment by dminor** [comment]
Thank you for the report, sorry I have not been paying attention to this project, it was something I did for fun a long time ago, and there's probably better options like pyephem for most people.
